apiVersion: v1
kind: Service
metadata:
  name: machine-learning-aplication-service
spec:
  selector:
    app: machine-learning-aplication
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
